spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/mercadolivro
    username: root
    password: root
  jackson:
    default-property-inclusion: non_null

jwt:
  secret: 254bbdf6-9044-400c-98a2-a88262b57636
  expiration: 999999